server:
  port: 28081

spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:config/prod/server.yml
      - classpath:config/prod/datasource.yml
      - classpath:config/prod/jpa.yml
      - classpath:config/prod/flyway.yml
      - classpath:config/prod/cache.yml
      - classpath:config/prod/web.yml
      - classpath:config/prod/aws.yml
      - classpath:config/prod/dynamodb.yml
      - classpath:config/prod/lock.yml
      - classpath:config/prod/crypto.yml
      - classpath:config/prod/kafka.yml
      - classpath:config/prod/logging.yml

  batch:
    job:
      name: ${JOB_NAME:NONE}          # 실행할 배치 잡 이름 (기본 NONE → 자동 실행 안 함)
      enabled: true                   # 애플리케이션 기동 시 Job 실행 여부
    jdbc:
      initialize-schema: always       # 배치 메타테이블 자동 생성 (RDS 초기가동/로컬 포함)
