server:
  port: 28081

spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:config/local/server.yml
      - classpath:config/local/datasource.yml
      - classpath:config/local/jpa.yml
      - classpath:config/local/flyway.yml
      - classpath:config/local/cache.yml
      - classpath:config/local/web.yml
      - classpath:config/local/aws.yml
      - classpath:config/local/dynamodb.yml
      - classpath:config/local/lock.yml
      - classpath:config/local/crypto.yml
      - classpath:config/local/kafka.yml
      - classpath:config/local/logging.yml

  batch:
    job:
      name: ${JOB_NAME:NONE}          # 실행할 배치 잡 이름 (기본 NONE → 자동 실행 안 함)
      enabled: true                   # 애플리케이션 기동 시 Job 실행 여부
    jdbc:
      initialize-schema: always       # 배치 메타테이블 자동 생성 (RDS 초기가동/로컬 포함)
