spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect.storage_engine: innodb
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}
        connection.provider_disables_autocommit: true
        jdbc.batch_size: ${chunkSize:1000}
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC
        timezone.default_storage: NORMALIZE
        order_updates: true
        order_inserts: true
        jdbc.batch_versioned_data: true

  config.activate.on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}/order
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    hikari:
      connection-timeout: 3000
      max-lifetime: 58000  # 58s
      maximum-pool-size: 10
      auto-commit: false
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
        useUnicode: true
        characterEncoding: utf-8
        serverTimezone: UTC
        rewriteBatchedStatements: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 32       # 동시에 사용할 수 있는 최대 커넥션 수
        max-idle: 16         # idle 상태로 유지할 수 있는 커넥션 수
        min-idle: 4          # 최소 idle 커넥션 수 확보 (예열 용도)
        max-wait: 2000ms     # 커넥션 풀에서 커넥션을 기다릴 수 있는 최대 시간

# openssl rand -base64 32 또는 12로 key/iv 생성 추천
encrypt:
  key: YmFzZTY0ZW5jb2RlZC1rZXktdGhhdC1pcy0zMmJ5dGVsbG9uZw== # Base64 인코딩된 32byte 키
  iv: bXktMTJieXRlLWdjbS12ZWN0 # Base64 인코딩된 12byte IV
