spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect.storage_engine: innodb
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}
        connection.provider_disables_autocommit: true
        jdbc.batch_size: ${chunkSize:1000}
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC
        timezone.default_storage: NORMALIZE
        order_updates: true
        order_inserts: true
        jdbc.batch_versioned_data: true

  config.activate.on-profile: beta
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}/order
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    hikari:
      connection-timeout: 3000
      max-lifetime: 58000  # 58s
      maximum-pool-size: 32
      auto-commit: false
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
        useUnicode: true
        characterEncoding: utf-8
        serverTimezone: UTC
        rewriteBatchedStatements: true

  redis:
    enabled: true
    # 1) URI 우선 (TLS는 rediss://)
    # uri: rediss://my-redis.example.com:6380
    # 2) 없으면 host/port
    host: 127.0.0.1
    port: 6379
    # password: your-pass
    # database: 0

    # (선택) clientName 설정/추론
    # client-name: my-app-redis
    # enable-default-client-name: true
    # default-client-name: order-core

    # 직렬화 신뢰 패키지
    trusted-package: org.example.order

    # 타임아웃/풀 설정
    command-timeout-seconds: 3
    shutdown-timeout-seconds: 3
    pool-max-active: 64
    pool-max-idle: 32
    pool-min-idle: 8
    pool-max-wait: 2000

jpa:
  enabled: false

dynamodb:
  enabled: true
  endpoint: http://localhost:4566
  region: ap-northeast-2      # endpoint만 줄 때 region 미지정이면 내부 기본값(us-east-1) 사용
  access-key: local
  secret-key: local
  table-name: order_dynamo

aws:
  secrets-manager:
    enabled: true                   # Secret Manager 사용 여부
    region: ap-northeast-2          # AWS 리전 (예: 서울 리전)
    secret-name: myapp/secret-key   # Secret 이름 (클래스 필드명과 일치)
    scheduler-enabled: true         # Scheduler 사용 여부
    refresh-interval-millis: 300000 # Secret 갱신 주기 (5분 = 300,000ms)
    fail-fast: true                 # Secret 조회 실패 시 앱 기동 중단 여부

lock:
  redisson:
    enabled: true
    address: redis://127.0.0.1:6379
    database: 0
    wait-time: 3000       # ms
    lease-time: 10000     # ms
    retry-interval: 150   # ms

  named:
    enabled: true
    wait-time: 3000       # ms
    retry-interval: 150   # ms

crypto:
  enabled: true
  props:
    seed: true

encrypt:
  aes128:
    key: ${AES128_KEY}   # AES-128 CBC용 (16바이트)
  aes256:
    key: ${AES256_KEY}   # AES-256 CBC용 (32바이트)
  aesgcm:
    key: ${AESGCM_KEY}   # AES-GCM 256용 (32바이트)
  hmac:
    key: ${HMAC_KEY}     # HMAC-SHA256용 (32바이트)

