spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect.storage_engine: innodb
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}
        connection.provider_disables_autocommit: true
        jdbc.batch_size: ${chunkSize:1000}
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC
        timezone.default_storage: NORMALIZE
        order_updates: true
        order_inserts: true
        jdbc.batch_versioned_data: true

  config.activate.on-profile: beta
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}/order
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    hikari:
      connection-timeout: 3000
      max-lifetime: 58000  # 58s
      maximum-pool-size: 32
      auto-commit: false
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
        useUnicode: true
        characterEncoding: utf-8
        serverTimezone: UTC
        rewriteBatchedStatements: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    trusted-package: org.example.order

aws:
  dynamodb:
    endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
    region: ap-northeast-2
    accessKey: test
    secretKey: test

  kms:
    region: ap-northeast-2

lock:
  redisson:
    address: redis://localhost:6379
    password: # 선택
    database: 0
    wait-time: 3000
    lease-time: 10000

  named:
    wait-time: 5000       # milliseconds
    retry-interval: 100   # 재시도 간격 (ex: 100ms)

security:
  jwt:
    secret: ZGVtb19iYXNlNjRfc2VjcmV0X3Rva2VuX2tleQ==
    access-token-validity: 900000   # 15 minutes (in ms)
    refresh-token-validity: 1209600000 # 14 days (in ms)
    header: Authorization
    prefix: Bearer

  oauth2:
    client:
      registration:
        google:
          client-id: YOUR_GOOGLE_CLIENT_ID
          client-secret: YOUR_GOOGLE_CLIENT_SECRET
          scope: profile, email
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          client-name: Google
        kakao:
          client-id: YOUR_KAKAO_REST_API_KEY
          client-secret: YOUR_KAKAO_CLIENT_SECRET  # 카카오에서는 보통 생략 가능
          client-authentication-method: client_secret_post
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope: profile_nickname, account_email
          client-name: Kakao
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

encrypt:
  kms-region: ap-northeast-2
  aes128:
    key: ${AES128_KEY} #(16 bytes)
  aes256:
    key: ${AES256_KEY} # 32 bytes
  aesgcm:
    key: ${AESGCM_KEY} # 32 bytes
  hmac:
    key: ${HMAC_KEY}   # 32 bytes

# Spring Gateway + AWS Clpud Map 용 설정
#spring:
#  application:
#    name: gateway-service
#
#  cloud:
#    discovery:
#      enabled: true
#
#    aws:
#      region:
#        static: ap-northeast-2
#      stack:
#        auto: false
#      cloud-map:
#        discovery:
#          enabled: true
#          service-id: gateway-service
#          namespace: msa.local
#
#server:
#  port: 8080
