spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect.storage_engine: innodb
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}
        connection.provider_disables_autocommit: true
        jdbc.batch_size: ${chunkSize:1000}
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC
        timezone.default_storage: NORMALIZE
        order_updates: true
        order_inserts: true
        jdbc.batch_versioned_data: true

  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3312/order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      max-lifetime: 58000  # 58s
      maximum-pool-size: 16
      auto-commit: false
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
        useUnicode: true
        characterEncoding: utf-8
        serverTimezone: UTC
        rewriteBatchedStatements: true

  redis:
    enabled: true
    # uri
    uri: redis://:secret123@redis-auto.example.com:6380/1
    client-name: order-service
    #     host/port
    #     host: redis-primary.example.com
    #     port: 6379
    password: secret123
    database: 0
    client-name: order-service
    trusted-package: org.example.order
    command-timeout-seconds: 5
    shutdown-timeout-seconds: 5

aws:
  dynamodb:
    endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
    region: ap-northeast-2
    accessKey: test
    secretKey: test

  secrets-manager:
    region: ap-northeast-2          # AWS 리전 (예: 서울 리전)
    secret-name: myapp/secret-key    # 저장한 Secret 이름
    refresh-interval-millis: 300000  # 키 갱신 주기 (5분 = 300,000ms)

lock:
  redisson:
    address: redis://localhost:6379
    password: # 선택
    database: 0
    wait-time: 3000
    lease-time: 10000

  named:
    wait-time: 5000       # milliseconds
    retry-interval: 100   # 재시도 간격 (ex: 100ms)

crypto:
  enabled: true
  props:
    seed: true

encrypt:
  aes128:
    key: dGhpc2lzMTZieXRla2V5IQ==                       # AES-128 CBC용 (16바이트)
  aes256:
    key: bXlTZWNyZXRLZXlTMjU2MjU2MjU2MjU2MjU2MjU2MjU=   # AES-256 CBC용 (32바이트)
  aesgcm:
    key: bXlTMzJiYnl0ZXNnY21rZXlzdXBlcnNlY3JldGtleTE=   # AES-GCM 256용 (32바이트)
  hmac:
    key: test-hmac-secret                               # HMAC-SHA256용 (32바이트)
