server:
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: beta
    import:
      - application-core-beta.yml
      - application-kafka-beta.yml
  task:
    scheduling:
      pool:
        size: 5
  lifecycle:
    timeout-per-shutdown-phase: 30s

aws:
  credential:
    enabled: false
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${BUCKET}
    default-folder: ${DEFAULT_FOLDER}

web-client:
  url:
    order: "http://localhost:8080/orders"

logging:
  file:
    path: /app/logs
  level:
    org.example: debug
