spring:
  main:
    web-application-type: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

lock:
  enabled: true
  named:
    enabled: false
    wait-time: 3000
    retry-interval: 150
  redisson:
    enabled: false
    wait-time: 3000
    lease-time: 10000
    retry-interval: 150

logging:
  level:
    org.springframework: WARN
