spring:
  datasource:
    url: jdbc:tc:mysql:8.3.0:///order_it?TC_REUSABLE=true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    connect-retries: 10
    table: flyway_schema_history

jpa:
  enabled: true

dynamodb:
  enabled: false

redis:
  enabled: false

lock:
  enabled: false
