spring:
  main:
    web-application-type: none
  # 통합 테스트에선 DataSource, Redis endpoint 를 Testcontainers 로 주입하므로
  # datasource/jpa 기본값은 AbstractIntegrationTest 가 동적으로 설정합니다.

# 기본은 모두 OFF(필수 스위치는 IT 클래스에서 properties 또는 DynamicPropertySource 로 ON)
secrets:
  enabled: false

aws:
  secrets-manager:
    enabled: false

dynamodb:
  enabled: false

# - named.enabled: false (개별 테스트에서 ON)
# - redisson.enabled: false (개별 테스트에서 ON)
lock:
  enabled: true
  named:
    enabled: false
    wait-time: 3000
    retry-interval: 150
  redisson:
    enabled: false
    database: 0
    wait-time: 3000
    lease-time: 10000
    retry-interval: 150

crypto:
  enabled: false

logging:
  level:
    org.springframework.data.redis: DEBUG

tsid:
  enabled: true
  node-bits: 10
  zone-id: Asia/Seoul
  prefer-ec2-meta: true
