# ============================================================================
# application-kafka-local.yml
#  - 로컬 개발/테스트용
#  - MSK/IAM 비사용(ssl.enabled=false), 로컬 브로커(PLAINTEXT)로 접속
#  - producer/consumer를 명시적으로 켜고 끌 수 있도록 enabled 추가
#  - 기존 키 구조는 그대로 유지
# ============================================================================

kafka:
  # ------------------------------------------------------------------------
  # SSL/SASL : 로컬에선 일반적으로 필요 없음 → 끔
  # ------------------------------------------------------------------------
  ssl:
    enabled: false                          # 로컬 브로커가 PLAINTEXT면 반드시 false
    security-protocol: SASL_SSL             # (참고) MSK/IAM 쓸 때만 의미 있음
    sasl-mechanism: AWS_MSK_IAM
    sasl-jaas-config: software.amazon.msk.auth.iam.IAMLoginModule required;
    sasl-client-callback-handler-class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

  # ------------------------------------------------------------------------
  # 프로듀서
  #  - enabled=true : KafkaTemplate/ProducerFactory 활성화
  #  - bootstrap-servers : 로컬 멀티브로커(예: 9092/9093/9094)
  # ------------------------------------------------------------------------
  producer:
    enabled: true                           # ✨ 로컬에서 기본 ON
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    # (선택) 필요 시 코드 확장해 아래 속성도 바인딩 가능
    # acks: all
    # linger-ms: 5
    # batch-size: 65536

  # ------------------------------------------------------------------------
  # 토픽 매핑
  #  - 서비스 도메인별 로컬 토픽 이름
  #  - region 세분화가 필요하면 항목에 regionCode 추가 가능
  # ------------------------------------------------------------------------
  topic:
    - category: order-local
      name: "local-order-local"
    - category: order-api
      name: "local-order-api"
    - category: order-crud
      name: "local-order-crud"
    - category: order-remote
      name: "local-order-remote"

  # ------------------------------------------------------------------------
  # 컨슈머
  #  - enabled=true : ListenerContainerFactory 활성화(@EnableKafka 포함)
  #  - ackMode=MANUAL_IMMEDIATE 정책(코드 기본값)과 맞춰 auto-commit=false
  #  - auto-offset-reset=earliest : 신규 그룹은 처음부터 읽기
  # ------------------------------------------------------------------------
  consumer:
    enabled: true                           # ✨ 로컬에서 기본 ON
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094

    option:
      max-fail-count: 1
      max-poll-records: 1000
      fetch-max-wait-ms: 500
      fetch-max-bytes: 52428800            # 50 MiB
      max-poll-interval-ms: 300000         # 5분
      idle-between-polls: 0
      auto-offset-reset: "earliest"
      enable-auto-commit: false            # 수동 커밋(ack.acknowledge())과 일치
