# ============================================================================
# application-kafka-local.yml
#  - 로컬 개발/테스트용
#  - MSK/IAM 비사용(ssl.enabled=false), 로컬 브로커(PLAINTEXT)로 접속
#  - producer/consumer를 명시적으로 켜고 끌 수 있도록 enabled 추가
#  - 기존 키 구조는 그대로 유지
#  - Docker Compose 기준: 호스트 접속 포트 = localhost:29092
# ============================================================================

kafka:
  # ------------------------------------------------------------------------
  # SSL/SASL : 로컬에선 일반적으로 필요 없음 → 끔
  # ------------------------------------------------------------------------
  ssl:
    enabled: false
    security-protocol: SASL_SSL
    sasl-mechanism: AWS_MSK_IAM
    sasl-jaas-config: software.amazon.msk.auth.iam.IAMLoginModule required;
    sasl-client-callback-handler-class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

  # ------------------------------------------------------------------------
  # 프로듀서
  #  - enabled=true : KafkaTemplate/ProducerFactory 활성화
  #  - bootstrap-servers : 로컬 단일 브로커(외부 노출 29092)
  # ------------------------------------------------------------------------
  producer:
    enabled: true
    bootstrap-servers: 127.0.0.1:29092
    # (선택) 필요 시 코드 확장해 아래 속성도 바인딩 가능
    # acks: all
    # linger-ms: 5
    # batch-size: 65536

  # ------------------------------------------------------------------------
  # 토픽 매핑
  #  - 서비스 도메인별 로컬 토픽 이름
  #  - region 세분화가 필요하면 항목에 regionCode 추가 가능
  # ------------------------------------------------------------------------
  topic:
    - category: ORDER_LOCAL
      name: "local-order-local"
    - category: ORDER_API
      name: "local-order-api"
    - category: ORDER_CRUD
      name: "local-order-crud"
    - category: ORDER_REMOTE
      name: "local-order-remote"
    - category: ORDER_DLQ
      name: "local-order-dead-letter"
    - category: ORDER_ALARM
      name: "local-order-alarm"

  # ------------------------------------------------------------------------
  # 컨슈머
  #  - enabled=true : ListenerContainerFactory 활성화(@EnableKafka 포함)
  #  - ackMode=MANUAL_IMMEDIATE 정책(코드 기본값)과 맞춰 auto-commit=false
  #  - auto-offset-reset=earliest : 신규 그룹은 처음부터 읽기
  # ------------------------------------------------------------------------
  consumer:
    enabled: true
    bootstrap-servers: 127.0.0.1:29092

    option:
      max-fail-count: 1
      max-poll-records: 1000
      fetch-max-wait-ms: 500
      fetch-max-bytes: 52428800            # 50 MiB
      max-poll-interval-ms: 300000         # 5분
      idle-between-polls: 0
      auto-offset-reset: "earliest"
      enable-auto-commit: false            # 수동 커밋(ack.acknowledge())과 일치
