spring:
  redis:
    enabled: false
    host: localhost
    port: 6379
    database: 0
    password: order1234
    trusted-package: org.example.order
    command-timeout-seconds: 3
    shutdown-timeout-seconds: 3
    pool-max-active: 32
    pool-max-idle: 16
    pool-min-idle: 8
    pool-max-wait: 2000

management:
  health:
    redis:
      enabled: false
