crypto:
  enabled: false
  props:
    seed: false

app:
  crypto:
    keys:
      orderAesGcm:
        alias: "order.aesgcm"
        encryptor: "AES-GCM"
        kid: "key-2025-09-27"
      orderAes256:
        alias: "order.aes256"
        encryptor: "AES-256"
        version: 3
      orderAes128:
        alias: "order.aes128"
        encryptor: "AES-128"
        version: 2
      orderHmac:
        alias: "order.hmac"
        encryptor: "HMAC_SHA256"
        kid: "key-2025-01-10"
