# ================== application-local.yml (FINAL v3) ==================
# (★ CHANGED/ADDED 주석으로 표시)
# - LocalStack: http://localhost:4566 (S3, DynamoDB, Secrets Manager)
# - 로그 디렉토리: /app/logs
# - Kafka: localhost:29092
# ======================================================================

# ===== Server =====
server:
  shutdown: graceful

# ===== Spring =====
spring:
  config:
    activate:
      on-profile: local

  lifecycle:
    timeout-per-shutdown-phase: 30s

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect.storage_engine: innodb
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}
        connection.provider_disables_autocommit: true
        jdbc.batch_size: ${chunkSize:1000}
        highlight_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC
        timezone.default_storage: NORMALIZE
        order_updates: true
        order_inserts: true
        jdbc.batch_versioned_data: true
        show-sql: true

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    connect-retries: 10
    clean-disabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/order_local?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: order
    password: order1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      max-lifetime: 58000
      maximum-pool-size: 16
      auto-commit: false
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
        useUnicode: true
        characterEncoding: utf-8
        serverTimezone: UTC
        rewriteBatchedStatements: true

# ===== Logging =====
logging:
  file:
    path: /app/logs
  level:
    org.example: debug
    org.hibernate.orm.jdbc.bind: debug

# ===== Redis (OFF) =====
redis:
  enabled: false
  host: 127.0.0.1
  port: 6379
  trusted-package: org.example.order
  command-timeout-seconds: 3
  shutdown-timeout-seconds: 3
  pool-max-active: 32
  pool-max-idle: 16
  pool-min-idle: 8
  pool-max-wait: 2000

jpa:
  enabled: true

# ===== AWS + S3 + Secrets (MERGED) =====
aws:
  region: ap-northeast-2
  endpoint: http://localhost:4566                   # ★ LocalStack endpoint
  credential:
    enabled: true                                   # ★ CHANGED: local에서 명시적 사용
    access-key: local
    secret-key: local
  s3:
    enabled: true
    bucket: my-local-bucket
    default-folder: logs
  secrets-manager:
    enabled: true
    region: ap-northeast-2
    secret-name: myapp/secret-key                   # ★ CHANGED: bootstrap과 일치
    scheduler-enabled: true
    refresh-interval-millis: 300000
    fail-fast: true

# ===== DynamoDB (요청값 그대로 반영) =====
dynamodb:
  enabled: true                                     # ★ 요청 반영
  endpoint: http://localhost:4566
  region: ap-northeast-2
  access-key: local
  secret-key: local
  table-name: order_dynamo

# ===== Kafka =====
kafka:
  enabled: true
  ssl:
    enabled: false
    security-protocol: SASL_SSL
    sasl-mechanism: AWS_MSK_IAM
    sasl-jaas-config: software.amazon.msk.auth.iam.IAMLoginModule required;
    sasl-client-callback-handler-class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

  producer:
    enabled: true
    bootstrap-servers: 127.0.0.1:29092

  topic:
    - category: ORDER_LOCAL
      name: "local-order-local"
    - category: ORDER_API
      name: "local-order-api"
    - category: ORDER_CRUD
      name: "local-order-crud"
    - category: ORDER_REMOTE
      name: "local-order-remote"
    - category: ORDER_DLQ
      name: "local-order-dead-letter"
    - category: ORDER_ALARM
      name: "local-order-alarm"

  consumer:
    enabled: true
    bootstrap-servers: 127.0.0.1:29092
    option:
      max-fail-count: 1
      max-poll-records: 1000
      fetch-max-wait-ms: 500
      fetch-max-bytes: 52428800
      max-poll-interval-ms: 300000
      idle-between-polls: 0
      auto-offset-reset: "earliest"
      enable-auto-commit: false
