services:
  localstack:
    image: localstack/localstack:3
    restart: unless-stopped
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
    environment:
      - SERVICES=${LOCALSTACK_SERVICES:-s3,dynamodb,secretsmanager}
      - AWS_DEFAULT_REGION=${AWS_REGION:-ap-northeast-2}
      - DEBUG=${LOCALSTACK_DEBUG:-1}
      - PERSISTENCE=1
      - LS_TMP=/tmp/localstack
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack/init/ready.d:/etc/localstack/init/ready.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:4566/_localstack/health | grep -q '\"initialized\": true'" ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

volumes:
  localstack_data:
    name: localstack_data

networks:
  default:
    name: aws_default
    driver: bridge
