spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:config/local/server.yml
      - classpath:config/local/datasource.yml
      - classpath:config/local/jpa.yml
      - classpath:config/local/flyway.yml
      - classpath:config/local/cache.yml
      - classpath:config/local/web.yml
      - classpath:config/local/aws.yml
      - classpath:config/local/dynamodb.yml
      - classpath:config/local/lock.yml
      - classpath:config/local/crypto.yml
      - classpath:config/local/kafka.yml
      - classpath:config/local/logging.yml

server:
  port: 8080
