aws:
  region: ap-northeast-2
  endpoint: http://localhost:4566

  credential:
    enabled: false
    access-key: dev
    secret-key: dev

  s3:
    enabled: false
    bucket: my-local-bucket
    default-folder: logs
    auto-create: true
    create-prefix-placeholder: true

  secrets-manager:
    enabled: false
    secret-name: myapp/secret-key
    scheduler-enabled: false
    refresh-interval-millis: 300000
    fail-fast: true
