spring:
  jpa:
    hibernate:
      ddl-auto: none      # local
      # ddl-auto: validate  # dev, beta, prod
    open-in-view: false
    properties:
      hibernate:
        # Hibernate 6은 dialect 자동선택 가능(명시 제거 권장). 필요한 경우만 지정.
        # dialect: org.hibernate.dialect.MySQLDialect

        # 저장소/쿼리 성능 및 가독
        highlight_sql: true
        use_sql_comments: true
        show_sql: true

        # 배치/정렬 최적화
        default_batch_fetch_size: ${chunkSize:1000}
        jdbc.batch_size: ${chunkSize:1000}
        jdbc.batch_versioned_data: true
        order_inserts: true
        order_updates: true

        # 트랜잭션/타임존
        connection.provider_disables_autocommit: true
        jdbc.time_zone: UTC
        timezone.default_storage: NORMALIZE

        # 기타
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        dialect.storage_engine: innodb

jpa:
  enabled: true
