spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:config/prod/server.yml
      - classpath:config/prod/datasource.yml
      - classpath:config/prod/jpa.yml
      - classpath:config/prod/flyway.yml
      - classpath:config/prod/redis.yml
      - classpath:config/prod/web.yml
      - classpath:config/prod/aws.yml
      - classpath:config/prod/dynamodb.yml
      - classpath:config/prod/lock.yml
      - classpath:config/prod/crypto.yml
      - classpath:config/prod/kafka.yml
      - classpath:config/prod/logging.yml

server:
  port: 8081
