server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
    import:
      - application-core-prod.yml
      - application-kafka-prod.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
api:
  key: ${API_KEY}