server:
  port: 7711

spring:
  config:
    activate:
      on-profile: local
    import:
      - application-local.yml
      - application-kafka-local.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

order:
  api:
    infra:
      logging:
        filter-order: 10            # 공통 표준 키
        mdc-filter-order: 5
        incoming-header: X-Request-Id
        response-header: X-Request-Id
      security:
        enabled: true
        gateway:
          header: X-Internal-Auth
          secret: ${INTERNAL_GATEWAY_SECRET:local-secret}
        permit-all-patterns:
          - /actuator/health
          - /actuator/info
        authenticated-patterns:
          - /order/**
      format:
        write-dates-as-timestamps: false
