server:
  port: 7711

spring:
  config:
    activate:
      on-profile: local
    import:
      - application-core-local.yml
      - application-kafka-local.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
api:
  key: "test"