spring:
  config:
    activate:
      on-profile: beta
    import:
      - classpath:config/beta/server.yml
      - classpath:config/beta/datasource.yml
      - classpath:config/beta/jpa.yml
      - classpath:config/beta/flyway.yml
      - classpath:config/beta/redis.yml
      - classpath:config/beta/web.yml
      - classpath:config/beta/aws.yml
      - classpath:config/beta/dynamodb.yml
      - classpath:config/beta/lock.yml
      - classpath:config/beta/crypto.yml
      - classpath:config/beta/kafka.yml
      - classpath:config/beta/logging.yml

server:
  port: 8081
